language: go
sudo: required

notifications:
  email:
    recipients:
    - jpacker@ca.ibm.com
    - dominique.vernier@us.ibm.com
    on_success: change
    on_failure: always

go:
  - "1.8"

before_install:
- make glide-install
- make copyright-check
- make
